[package]
name = "syn-grep"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
rayon = "1.9.0"
serde = { version = "1.0.197", features = ["derive"] }
syn = { version="2.0.52", features=["full", "visit"]}
