name: Test

env:
    RUST_BACKTRACE: 1

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build with cargo
      run: cargo build --all --verbose
    - name: Run cargo tests
      run: cargo test --all --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check extractor
      run: python3 extractor-test/test_extractor.py
    - name: Compile the example packages
      run: |
        mkdir ../workspace
        cp CrateList-example.json CrateList.json
        cargo run -- compile
